import { AppFooter } from "@/components/AppFooter";
import { AppHeader } from "@/components/AppHeader";
import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppHeader />
        <div className="min-h-min-[100vh]">{children}</div>
        <AppFooter />
      </body>
    </html>
  );
}
